from __future__ import annotations

from typing import Any, Dict, List


def perm(
    service: str,
    apis: List[str],
    actions: List[str],
    evidence: List[str],
    capability: str,
    classification: str = "required",
    purpose: str = "",
) -> Dict[str, Any]:
    return {
        "service": service,
        "apis": apis,
        "actions": actions,
        "classification": classification,
        "evidence": evidence,
        "capability": capability,
        "purpose": purpose or capability,
    }


AWS_INVENTORY_PERMISSIONS = [
    perm(
        "EC2",
        ["DescribeInstances", "DescribeVpcs", "DescribeSecurityGroups"],
        ["ec2:DescribeInstances", "ec2:DescribeVpcs", "ec2:DescribeSecurityGroups"],
        ["EC2 inventory", "VPC inventory", "security groups"],
        "Inventory Collection",
        purpose="Enumerate compute instances, VPCs, and security groups for baseline asset inventory.",
    ),
    perm(
        "S3",
        ["ListBuckets"],
        ["s3:ListAllMyBuckets"],
        ["S3 buckets"],
        "Inventory Collection",
        purpose="List buckets that should be included in configuration and exposure review.",
    ),
    perm(
        "IAM",
        ["ListUsers", "ListRoles"],
        ["iam:ListUsers", "iam:ListRoles"],
        ["IAM users", "IAM roles"],
        "Identity Inventory",
        purpose="Discover human and workload identities in scope for identity review.",
    ),
    perm(
        "Lambda",
        ["ListFunctions"],
        ["lambda:ListFunctions"],
        ["Lambda functions"],
        "Inventory Collection",
        purpose="Enumerate serverless functions included in the assessment inventory.",
    ),
    perm(
        "RDS",
        ["DescribeDBInstances"],
        ["rds:DescribeDBInstances"],
        ["RDS instances"],
        "Inventory Collection",
        purpose="Discover managed database instances included in the assessment scope.",
    ),
]


PROWLER_PERMISSIONS = [
    perm(
        "IAM",
        [
            "GetAccountSummary",
            "GetAccountPasswordPolicy",
            "GenerateCredentialReport",
            "GetCredentialReport",
            "ListAccountAliases",
            "ListUsers",
            "ListRoles",
            "ListPolicies",
            "GetPolicy",
            "GetPolicyVersion",
        ],
        [
            "iam:GetAccountSummary",
            "iam:GetAccountPasswordPolicy",
            "iam:GenerateCredentialReport",
            "iam:GetCredentialReport",
            "iam:ListAccountAliases",
            "iam:ListUsers",
            "iam:ListRoles",
            "iam:ListPolicies",
            "iam:GetPolicy",
            "iam:GetPolicyVersion",
        ],
        ["IAM configuration", "Credential hygiene", "Password policy state"],
        "Identity and Credential Review",
        purpose="Validate IAM hardening, password policy, and credential hygiene posture.",
    ),
    perm(
        "EC2",
        [
            "DescribeInstances",
            "DescribeImages",
            "DescribeAddresses",
            "DescribeVolumes",
        ],
        [
            "ec2:DescribeInstances",
            "ec2:DescribeImages",
            "ec2:DescribeAddresses",
            "ec2:DescribeVolumes",
        ],
        ["Compute posture", "Volume encryption posture"],
        "Compute Configuration Review",
        purpose="Review compute exposure, instance posture, and encrypted storage configuration.",
    ),
    perm(
        "VPC",
        [
            "DescribeVpcs",
            "DescribeSubnets",
            "DescribeSecurityGroups",
            "DescribeSecurityGroupRules",
            "DescribeRouteTables",
            "DescribeNetworkAcls",
            "DescribeInternetGateways",
            "DescribeNatGateways",
            "DescribeTransitGateways",
            "DescribeVpcEndpoints",
            "DescribeVpnGateways",
            "DescribeVpnConnections",
            "DescribeNetworkInterfaces",
            "DescribeFlowLogs",
        ],
        [
            "ec2:DescribeVpcs",
            "ec2:DescribeSubnets",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSecurityGroupRules",
            "ec2:DescribeRouteTables",
            "ec2:DescribeNetworkAcls",
            "ec2:DescribeInternetGateways",
            "ec2:DescribeNatGateways",
            "ec2:DescribeTransitGateways",
            "ec2:DescribeVpcEndpoints",
            "ec2:DescribeVpnGateways",
            "ec2:DescribeVpnConnections",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DescribeFlowLogs",
        ],
        ["Network exposure", "Segmentation posture", "Flow log posture"],
        "Network Visibility",
        purpose="Inspect routing, segmentation, internet exposure, and logging coverage across VPC resources.",
    ),
    perm(
        "S3",
        [
            "ListBuckets",
            "GetBucketAcl",
            "GetBucketPolicyStatus",
            "GetBucketPublicAccessBlock",
            "GetBucketVersioning",
            "GetBucketEncryption",
            "GetBucketLogging",
            "GetBucketLifecycleConfiguration",
        ],
        [
            "s3:ListAllMyBuckets",
            "s3:GetBucketAcl",
            "s3:GetBucketPolicyStatus",
            "s3:GetBucketPublicAccessBlock",
            "s3:GetBucketVersioning",
            "s3:GetBucketEncryption",
            "s3:GetBucketLogging",
            "s3:GetBucketLifecycleConfiguration",
        ],
        ["Bucket exposure", "Bucket encryption", "Bucket logging", "Bucket lifecycle posture"],
        "Data Exposure Review",
        purpose="Review bucket-level configuration used to assess public exposure, encryption, versioning, and logging.",
    ),
    perm(
        "CloudTrail",
        ["DescribeTrails", "GetTrailStatus", "GetEventSelectors"],
        [
            "cloudtrail:DescribeTrails",
            "cloudtrail:GetTrailStatus",
            "cloudtrail:GetEventSelectors",
        ],
        ["CloudTrail configuration"],
        "Logging Validation",
        purpose="Validate account and region logging coverage, status, and selector configuration.",
    ),
    perm(
        "Config",
        [
            "DescribeConfigurationRecorders",
            "DescribeConfigurationRecorderStatus",
            "DescribeConfigRules",
            "DescribeComplianceByConfigRule",
            "DescribeConformancePacks",
        ],
        [
            "config:DescribeConfigurationRecorders",
            "config:DescribeConfigurationRecorderStatus",
            "config:DescribeConfigRules",
            "config:DescribeComplianceByConfigRule",
            "config:DescribeConformancePacks",
        ],
        ["Config recorder state", "Config rule compliance", "Conformance packs"],
        "Compliance Validation",
        purpose="Validate compliance recorder state and control coverage from AWS Config.",
    ),
    perm(
        "Security Hub",
        ["DescribeHub", "GetEnabledStandards", "GetFindings"],
        [
            "securityhub:DescribeHub",
            "securityhub:GetEnabledStandards",
            "securityhub:GetFindings",
        ],
        ["Security Hub enablement", "Enabled standards", "Security Hub findings"],
        "Security Service Validation",
        classification="optional",
        purpose="Retrieve enabled standards and findings when Security Hub is part of the customer environment.",
    ),
    perm(
        "GuardDuty",
        ["ListDetectors", "GetDetector", "ListFindings", "GetFindings"],
        [
            "guardduty:ListDetectors",
            "guardduty:GetDetector",
            "guardduty:ListFindings",
            "guardduty:GetFindings",
        ],
        ["GuardDuty detector state", "GuardDuty findings"],
        "Security Service Validation",
        classification="optional",
        purpose="Retrieve detector status and findings when GuardDuty is enabled.",
    ),
    perm(
        "CloudWatch",
        ["DescribeAlarms"],
        ["cloudwatch:DescribeAlarms"],
        ["Alarm coverage"],
        "Monitoring Validation",
        purpose="Review alarm coverage that supports detection and response validation.",
    ),
    perm(
        "CloudWatch Logs",
        ["DescribeLogGroups", "DescribeMetricFilters"],
        ["logs:DescribeLogGroups", "logs:DescribeMetricFilters"],
        ["Log group coverage", "Metric filter coverage"],
        "Monitoring Validation",
        purpose="Review log destinations and metric filters used for detection controls.",
    ),
    perm(
        "KMS",
        ["ListKeys", "DescribeKey", "GetKeyRotationStatus"],
        ["kms:ListKeys", "kms:DescribeKey", "kms:GetKeyRotationStatus"],
        ["KMS key posture", "Key rotation posture"],
        "Encryption Validation",
        purpose="Review customer-managed key state and rotation coverage referenced by security services.",
    ),
    perm(
        "Lambda",
        ["ListFunctions", "GetPolicy", "GetFunctionConfiguration"],
        ["lambda:ListFunctions", "lambda:GetPolicy", "lambda:GetFunctionConfiguration"],
        ["Lambda exposure", "Lambda runtime posture"],
        "Serverless Validation",
        purpose="Review function exposure, runtime posture, and network placement.",
    ),
    perm(
        "RDS",
        ["DescribeDBInstances", "DescribeDBSnapshots"],
        ["rds:DescribeDBInstances", "rds:DescribeDBSnapshots"],
        ["Database exposure", "Database backup posture"],
        "Database Configuration Review",
        purpose="Review managed database exposure, backup posture, and encryption settings.",
    ),
    perm(
        "ELB",
        [
            "DescribeLoadBalancers",
            "DescribeListeners",
            "DescribeTargetGroups",
            "DescribeLoadBalancerAttributes",
        ],
        [
            "elasticloadbalancing:DescribeLoadBalancers",
            "elasticloadbalancing:DescribeListeners",
            "elasticloadbalancing:DescribeTargetGroups",
            "elasticloadbalancing:DescribeLoadBalancerAttributes",
        ],
        ["Load balancer exposure"],
        "Ingress Review",
        purpose="Review internet-facing ingress and listener configuration exposed through load balancers.",
    ),
    perm(
        "Organizations",
        ["DescribeOrganization", "ListAccounts", "ListRoots"],
        [
            "organizations:DescribeOrganization",
            "organizations:ListAccounts",
            "organizations:ListRoots",
        ],
        ["Organization scope", "Account context"],
        "Enterprise Context",
        classification="optional",
        purpose="Add multi-account context and organization scope when Organizations is in use.",
    ),
    perm(
        "Backup",
        ["ListBackupPlans", "ListBackupVaults"],
        ["backup:ListBackupPlans", "backup:ListBackupVaults"],
        ["Backup program visibility"],
        "Resilience Validation",
        classification="optional",
        purpose="Add resilience context when AWS Backup is part of the environment.",
    ),
    perm(
        "Inspector",
        ["ListFindings", "ListCoverage"],
        ["inspector2:ListFindings", "inspector2:ListCoverage"],
        ["Inspector findings", "Workload coverage"],
        "Vulnerability Context",
        classification="optional",
        purpose="Incorporate native vulnerability findings when Inspector is enabled.",
    ),
    perm(
        "Macie",
        ["GetMacieSession", "ListFindings"],
        ["macie2:GetMacieSession", "macie2:ListFindings"],
        ["Macie enablement", "Macie findings"],
        "Sensitive Data Context",
        classification="optional",
        purpose="Incorporate sensitive-data discovery findings when Macie is enabled.",
    ),
    perm(
        "Detective",
        ["ListGraphs"],
        ["detective:ListGraphs"],
        ["Detective availability"],
        "Investigation Context",
        classification="optional",
        purpose="Record whether Detective investigation context is available to the assessment team.",
    ),
    perm(
        "Resource Explorer",
        ["ListIndexes", "Search"],
        ["resource-explorer-2:ListIndexes", "resource-explorer-2:Search"],
        ["Cross-service discovery context"],
        "Discovery Coverage",
        classification="optional",
        purpose="Improve inventory confidence with cross-service resource discovery when available.",
    ),
]


CLOUDSPLAINING_PERMISSIONS = [
    perm(
        "IAM",
        ["GetAccountAuthorizationDetails"],
        ["iam:GetAccountAuthorizationDetails"],
        ["Authorization details export", "IAM privilege analysis report"],
        "IAM Privilege Analysis",
        purpose="Export IAM authorization details for offline Cloudsplaining analysis.",
    )
]


ACCESS_ANALYZER_PERMISSIONS = [
    perm(
        "Access Analyzer",
        ["ListAnalyzers", "ListFindings"],
        ["access-analyzer:ListAnalyzers", "access-analyzer:ListFindings"],
        ["Analyzers", "Access findings"],
        "External Access Analysis",
        purpose="Enumerate analyzers and their findings for cross-account and public access review.",
    )
]


STEAMPIPE_PERMISSIONS = [
    perm(
        "EC2",
        ["DescribeInstances", "DescribeAddresses", "DescribeVolumes"],
        ["ec2:DescribeInstances", "ec2:DescribeAddresses", "ec2:DescribeVolumes"],
        ["Steampipe EC2 query results", "Steampipe EBS query results"],
        "Configuration Validation",
        purpose="Support compute, address, and encrypted-volume posture queries in the Steampipe pack.",
    ),
    perm(
        "VPC",
        [
            "DescribeVpcs",
            "DescribeSubnets",
            "DescribeSecurityGroups",
            "DescribeSecurityGroupRules",
            "DescribeRouteTables",
            "DescribeInternetGateways",
            "DescribeFlowLogs",
        ],
        [
            "ec2:DescribeVpcs",
            "ec2:DescribeSubnets",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSecurityGroupRules",
            "ec2:DescribeRouteTables",
            "ec2:DescribeInternetGateways",
            "ec2:DescribeFlowLogs",
        ],
        ["Steampipe VPC query results"],
        "Network Configuration Validation",
        purpose="Support Steampipe queries for public subnets, flow logs, routing, and security group exposure.",
    ),
    perm(
        "CloudTrail",
        ["DescribeTrails", "GetTrailStatus", "GetEventSelectors"],
        [
            "cloudtrail:DescribeTrails",
            "cloudtrail:GetTrailStatus",
            "cloudtrail:GetEventSelectors",
        ],
        ["Steampipe CloudTrail query results"],
        "Logging Validation",
        purpose="Support Steampipe trail configuration, validation, and encryption checks.",
    ),
    perm(
        "Config",
        ["DescribeConfigurationRecorders", "DescribeConfigurationRecorderStatus"],
        [
            "config:DescribeConfigurationRecorders",
            "config:DescribeConfigurationRecorderStatus",
        ],
        ["Steampipe Config query results"],
        "Compliance Validation",
        classification="optional",
        purpose="Support Steampipe recorder-state queries when AWS Config is available.",
    ),
    perm(
        "GuardDuty",
        ["ListDetectors", "GetDetector", "ListFindings", "GetFindings"],
        [
            "guardduty:ListDetectors",
            "guardduty:GetDetector",
            "guardduty:ListFindings",
            "guardduty:GetFindings",
        ],
        ["Steampipe GuardDuty query results"],
        "Threat Detection Validation",
        classification="optional",
        purpose="Support Steampipe detector-status and findings queries when GuardDuty is enabled.",
    ),
    perm(
        "IAM",
        [
            "GetAccountPasswordPolicy",
            "GenerateCredentialReport",
            "GetCredentialReport",
            "ListUsers",
            "ListRoles",
            "ListAccessKeys",
            "ListMFADevices",
            "ListPolicies",
            "GetPolicy",
            "GetPolicyVersion",
        ],
        [
            "iam:GetAccountPasswordPolicy",
            "iam:GenerateCredentialReport",
            "iam:GetCredentialReport",
            "iam:ListUsers",
            "iam:ListRoles",
            "iam:ListAccessKeys",
            "iam:ListMFADevices",
            "iam:ListPolicies",
            "iam:GetPolicy",
            "iam:GetPolicyVersion",
        ],
        ["Steampipe IAM query results", "Credential hygiene evidence"],
        "Identity Hygiene Validation",
        purpose="Support MFA, password policy, access-key-age, and wildcard-permission queries in the Steampipe pack.",
    ),
    perm(
        "KMS",
        ["ListKeys", "DescribeKey", "GetKeyRotationStatus"],
        ["kms:ListKeys", "kms:DescribeKey", "kms:GetKeyRotationStatus"],
        ["Steampipe KMS query results"],
        "Encryption Validation",
        classification="optional",
        purpose="Support key-state and rotation checks referenced by GuardDuty-related queries.",
    ),
    perm(
        "Lambda",
        ["ListFunctions", "GetPolicy", "GetFunctionConfiguration"],
        ["lambda:ListFunctions", "lambda:GetPolicy", "lambda:GetFunctionConfiguration"],
        ["Steampipe Lambda query results"],
        "Serverless Validation",
        purpose="Support public access, runtime, VPC, and DLQ posture queries for Lambda.",
    ),
    perm(
        "RDS",
        ["DescribeDBInstances", "DescribeDBSnapshots"],
        ["rds:DescribeDBInstances", "rds:DescribeDBSnapshots"],
        ["Steampipe RDS query results"],
        "Database Configuration Validation",
        purpose="Support public exposure, backup, snapshot, multi-AZ, and encryption checks for RDS.",
    ),
    perm(
        "S3",
        [
            "ListBuckets",
            "GetBucketAcl",
            "GetBucketPolicyStatus",
            "GetBucketPublicAccessBlock",
            "GetBucketVersioning",
            "GetBucketEncryption",
            "GetBucketLogging",
            "GetBucketObjectLockConfiguration",
        ],
        [
            "s3:ListAllMyBuckets",
            "s3:GetBucketAcl",
            "s3:GetBucketPolicyStatus",
            "s3:GetBucketPublicAccessBlock",
            "s3:GetBucketVersioning",
            "s3:GetBucketEncryption",
            "s3:GetBucketLogging",
            "s3:GetBucketObjectLockConfiguration",
        ],
        ["Steampipe S3 query results"],
        "Data Exposure Validation",
        purpose="Support S3 bucket exposure, encryption, versioning, logging, and object-lock posture queries.",
    ),
]


CONFIG_AGGREGATOR_PERMISSIONS = [
    perm(
        "Config",
        [
            "DescribeConfigurationAggregators",
            "DescribeComplianceByConfigRule",
            "DescribeConfigRules",
            "DescribeConformancePacks",
            "ListAggregateDiscoveredResources",
        ],
        [
            "config:DescribeConfigurationAggregators",
            "config:DescribeComplianceByConfigRule",
            "config:DescribeConfigRules",
            "config:DescribeConformancePacks",
            "config:ListAggregateDiscoveredResources",
        ],
        ["Config compliance and resource inventory"],
        "Compliance Validation",
        purpose="Read aggregator-level compliance posture and aggregated EC2 inventory from AWS Config.",
    )
]


CARTOGRAPHY_PERMISSIONS = [
    perm(
        "IAM",
        [
            "GetAccountAuthorizationDetails",
            "GenerateCredentialReport",
            "GetCredentialReport",
            "ListUsers",
            "ListRoles",
            "ListPolicies",
            "GetPolicy",
            "GetPolicyVersion",
        ],
        [
            "iam:GetAccountAuthorizationDetails",
            "iam:GenerateCredentialReport",
            "iam:GetCredentialReport",
            "iam:ListUsers",
            "iam:ListRoles",
            "iam:ListPolicies",
            "iam:GetPolicy",
            "iam:GetPolicyVersion",
        ],
        ["Cartography identity graph summary"],
        "Relationship Mapping",
        classification="optional",
        purpose="Support graph ingestion of identities, policies, and trust relationships into the analyst-owned graph store.",
    ),
    perm(
        "EC2",
        [
            "DescribeInstances",
            "DescribeSecurityGroups",
            "DescribeSecurityGroupRules",
            "DescribeVpcs",
            "DescribeSubnets",
            "DescribeRouteTables",
            "DescribeNetworkInterfaces",
            "DescribeVolumes",
        ],
        [
            "ec2:DescribeInstances",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSecurityGroupRules",
            "ec2:DescribeVpcs",
            "ec2:DescribeSubnets",
            "ec2:DescribeRouteTables",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DescribeVolumes",
        ],
        ["Cartography infrastructure graph summary"],
        "Relationship Mapping",
        classification="optional",
        purpose="Support graph ingestion of compute, network, and attached-storage relationships.",
    ),
    perm(
        "S3",
        [
            "ListBuckets",
            "GetBucketAcl",
            "GetBucketPolicyStatus",
            "GetBucketPublicAccessBlock",
        ],
        [
            "s3:ListAllMyBuckets",
            "s3:GetBucketAcl",
            "s3:GetBucketPolicyStatus",
            "s3:GetBucketPublicAccessBlock",
        ],
        ["Cartography storage exposure summary"],
        "Relationship Mapping",
        classification="optional",
        purpose="Support graph ingestion of bucket exposure relationships.",
    ),
    perm(
        "Lambda",
        ["ListFunctions", "GetPolicy"],
        ["lambda:ListFunctions", "lambda:GetPolicy"],
        ["Cartography serverless graph summary"],
        "Relationship Mapping",
        classification="optional",
        purpose="Support graph ingestion of function resources and public invocation relationships.",
    ),
    perm(
        "RDS",
        ["DescribeDBInstances", "DescribeDBSnapshots"],
        ["rds:DescribeDBInstances", "rds:DescribeDBSnapshots"],
        ["Cartography database graph summary"],
        "Relationship Mapping",
        classification="optional",
        purpose="Support graph ingestion of database assets and snapshot relationships.",
    ),
    perm(
        "ELB",
        ["DescribeLoadBalancers", "DescribeTargetGroups"],
        [
            "elasticloadbalancing:DescribeLoadBalancers",
            "elasticloadbalancing:DescribeTargetGroups",
        ],
        ["Cartography ingress graph summary"],
        "Relationship Mapping",
        classification="optional",
        purpose="Support graph ingestion of ingress relationships exposed through load balancers.",
    ),
    perm(
        "Organizations",
        ["DescribeOrganization", "ListAccounts", "ListRoots"],
        [
            "organizations:DescribeOrganization",
            "organizations:ListAccounts",
            "organizations:ListRoots",
        ],
        ["Cartography organization summary"],
        "Relationship Mapping",
        classification="optional",
        purpose="Support graph ingestion of organization structure when Organizations is available.",
    ),
]


COLLECTOR_METADATA: Dict[str, Dict[str, Any]] = {
    "aws_inventory": {
        "name": "AWS Inventory",
        "purpose": "Baseline AWS asset inventory across selected regions and core services.",
        "estimated_runtime": "Low",
        "services_inspected": ["IAM", "EC2", "VPC", "S3", "Lambda", "RDS"],
        "evidence_produced": [
            "EC2 inventory",
            "VPC inventory",
            "security groups",
            "S3 buckets",
            "IAM users",
            "IAM roles",
            "Lambda functions",
            "RDS instances",
        ],
        "mitre_mapping": ["Discovery", "Resource Development"],
        "threat_scenarios_supported": [
            "Public compute exposure",
            "Identity privilege review",
            "Data exposure review",
        ],
        "writes_customer_aws": False,
        "notes": "",
        "permissions": AWS_INVENTORY_PERMISSIONS,
    },
    "prowler": {
        "name": "Prowler",
        "purpose": "Security posture checks for AWS services and control coverage.",
        "estimated_runtime": "Medium",
        "services_inspected": [
            "IAM",
            "EC2",
            "VPC",
            "S3",
            "CloudTrail",
            "Config",
            "CloudWatch",
            "CloudWatch Logs",
            "KMS",
            "Lambda",
            "RDS",
            "ELB",
            "Security Hub",
            "GuardDuty",
            "Organizations",
            "Backup",
            "Inspector",
            "Macie",
            "Detective",
            "Resource Explorer",
        ],
        "evidence_produced": [
            "Security findings",
            "CloudTrail status",
            "Config state",
            "Security Hub findings",
            "GuardDuty findings",
            "Network exposure posture",
        ],
        "mitre_mapping": ["Defense Evasion", "Credential Access", "Discovery"],
        "threat_scenarios_supported": [
            "Logging gaps",
            "Public data exposure",
            "Security service disablement",
        ],
        "writes_customer_aws": False,
        "notes": "Runs an external read-only scanner against customer AWS APIs.",
        "permissions": PROWLER_PERMISSIONS,
    },
    "cloudsplaining": {
        "name": "Cloudsplaining",
        "purpose": "IAM policy analysis for privilege escalation and access risk.",
        "estimated_runtime": "Low",
        "services_inspected": ["IAM"],
        "evidence_produced": [
            "Authorization details export",
            "IAM privilege analysis report",
        ],
        "mitre_mapping": ["Privilege Escalation", "Credential Access"],
        "threat_scenarios_supported": [
            "Privilege escalation path",
            "Over-privileged identity",
        ],
        "writes_customer_aws": False,
        "notes": "Uses AWS CLI `iam get-account-authorization-details`, then performs offline analysis.",
        "permissions": CLOUDSPLAINING_PERMISSIONS,
    },
    "access_analyzer": {
        "name": "IAM Access Analyzer",
        "purpose": "Cross-account and public access findings from IAM Access Analyzer.",
        "estimated_runtime": "Low",
        "services_inspected": ["Access Analyzer"],
        "evidence_produced": ["Analyzers", "Access findings"],
        "mitre_mapping": ["Discovery", "Collection"],
        "threat_scenarios_supported": [
            "Public resource access",
            "Cross-account exposure",
        ],
        "writes_customer_aws": False,
        "notes": "",
        "permissions": ACCESS_ANALYZER_PERMISSIONS,
    },
    "steampipe": {
        "name": "Steampipe",
        "purpose": "Query-driven cloud posture evidence and configuration visibility.",
        "estimated_runtime": "Medium",
        "services_inspected": [
            "IAM",
            "EC2",
            "VPC",
            "S3",
            "CloudTrail",
            "Config",
            "GuardDuty",
            "KMS",
            "Lambda",
            "RDS",
        ],
        "evidence_produced": ["Steampipe query results"],
        "mitre_mapping": ["Discovery", "Initial Access"],
        "threat_scenarios_supported": [
            "Public network exposure",
            "Logging gaps",
            "Configuration drift",
        ],
        "writes_customer_aws": False,
        "notes": "Service coverage is derived from the local Steampipe SQL query pack in `queries/aws/`.",
        "permissions": STEAMPIPE_PERMISSIONS,
    },
    "config_aggregator": {
        "name": "AWS Config",
        "purpose": "AWS Config recorder, rule, and conformance-pack visibility.",
        "estimated_runtime": "Low",
        "services_inspected": ["Config"],
        "evidence_produced": [
            "Configuration aggregators",
            "Config rule compliance",
            "Conformance packs",
            "Aggregated EC2 inventory",
        ],
        "mitre_mapping": ["Discovery"],
        "threat_scenarios_supported": ["Compliance recorder disabled", "Rule non-compliance"],
        "writes_customer_aws": False,
        "notes": "",
        "permissions": CONFIG_AGGREGATOR_PERMISSIONS,
    },
    "cartography": {
        "name": "Cartography",
        "purpose": "Relationship mapping between identities, assets, and trust paths.",
        "estimated_runtime": "High",
        "services_inspected": ["IAM", "EC2", "S3", "Lambda", "RDS", "ELB", "Organizations"],
        "evidence_produced": ["Cartography summary"],
        "mitre_mapping": ["Discovery", "Lateral Movement"],
        "threat_scenarios_supported": ["Attack path relationship mapping"],
        "writes_customer_aws": False,
        "notes": (
            "Uses an external Neo4j graph target with `cartography --update`; "
            "this writes only to the analyst-owned graph store, not customer AWS."
        ),
        "permissions": CARTOGRAPHY_PERMISSIONS,
    },
    "tenable": {
        "name": "Tenable",
        "purpose": "Imports cloud findings from Tenable when the customer already uses that platform.",
        "estimated_runtime": "Variable",
        "services_inspected": ["External Tenable APIs"],
        "evidence_produced": ["Tenable asset export"],
        "mitre_mapping": ["Discovery"],
        "threat_scenarios_supported": ["External exposure corroboration"],
        "writes_customer_aws": False,
        "notes": "Does not call customer AWS APIs; uses external Tenable read/list exports.",
        "permissions": [],
    },
}


CAPABILITY_VALIDATION_TARGETS: List[Dict[str, Any]] = [
    {"name": "STS", "service": "sts", "operation": "get_caller_identity", "params": {}, "mandatory": True},
    {"name": "Organizations", "service": "organizations", "operation": "describe_organization", "params": {}, "mandatory": False},
    {"name": "IAM", "service": "iam", "operation": "list_account_aliases", "params": {}, "mandatory": False},
    {"name": "EC2", "service": "ec2", "operation": "describe_regions", "params": {}, "mandatory": False},
    {"name": "VPC", "service": "ec2", "operation": "describe_vpcs", "params": {}, "mandatory": False},
    {"name": "CloudTrail", "service": "cloudtrail", "operation": "describe_trails", "params": {}, "mandatory": False},
    {"name": "Config", "service": "config", "operation": "describe_configuration_recorders", "params": {}, "mandatory": False},
    {"name": "Security Hub", "service": "securityhub", "operation": "describe_hub", "params": {}, "mandatory": False},
    {"name": "GuardDuty", "service": "guardduty", "operation": "list_detectors", "params": {}, "mandatory": False},
    {"name": "Access Analyzer", "service": "accessanalyzer", "operation": "list_analyzers", "params": {}, "mandatory": False},
    {"name": "S3", "service": "s3", "operation": "list_buckets", "params": {}, "mandatory": False, "regional": False},
    {"name": "Lambda", "service": "lambda", "operation": "list_functions", "params": {}, "mandatory": False},
    {"name": "EKS", "service": "eks", "operation": "list_clusters", "params": {}, "mandatory": False},
    {"name": "ECS", "service": "ecs", "operation": "list_clusters", "params": {}, "mandatory": False},
    {"name": "RDS", "service": "rds", "operation": "describe_db_instances", "params": {}, "mandatory": False},
    {"name": "ELB", "service": "elbv2", "operation": "describe_load_balancers", "params": {}, "mandatory": False},
    {"name": "CloudWatch", "service": "cloudwatch", "operation": "describe_alarms", "params": {}, "mandatory": False},
]


def enabled_collector_keys(config: Dict[str, Any]) -> List[str]:
    modules = config.get("modules", {}) or {}
    return [key for key, value in modules.items() if value and key in COLLECTOR_METADATA]


def collector_metadata_rows(config: Dict[str, Any] | None = None) -> List[Dict[str, Any]]:
    enabled = set(enabled_collector_keys(config or {})) if config is not None else None
    rows = []
    for key, item in COLLECTOR_METADATA.items():
        row = {"key": key, **item}
        row["enabled"] = enabled is None or key in enabled
        rows.append(row)
    return rows
